### ISSUE TITLE
Lab 3 - issue with HTML page

### ISSUE THREAD

**Issue by scp95** [MicrochipTech/PIC32MZW1_Workshop#4]
Hello,

I have an issue with the Lab3 (and also Lab4) help. 
I can connect my PC to the AP generated by the WFI32E module and I can see with the UART console that my PC is connected and the IP address is assigned. 
When I try to connect to the page http://192.168.1.1 I don't have response by the WFI32E module. Can someone help me?

![Console](https://user-images.githubusercontent.com/84172693/118234551-c4360980-b493-11eb-829d-d231b382be11.PNG)

**Comment by gd91** [comment]
For some lab, you might have to regenerate the demo code using Harmony3 after adding additional components or changing the existing configuration. Ensure that you use the same version or Harmony 3 components used in the original demo codebase while regenerating code. You can see the version dependencies of the demo in harmony-manifest-success.yml file found at src\firmware\src\config\pic32mz_w1_curiosity into Harmony3 content manager.

In case of a mismatch between the Harmony 3 components present in the demo and the ones available in disk, Harmony3 Configurator will popup a warning screen during launch. 

It is recommended to use the same versions used in the project while regenerating the project.

Checkout [here](https://github.com/MicrochipTech/PIC32MZW1_Curiosity_OOB#regenerating-the-demo-with-harmony-3)

For further support, please use [www.microchip.com/support](www.microchip.com/support)
