### ISSUE TITLE
It can't find the device in the demo web site.

### ISSUE THREAD

**Issue by HyungGyuKim76** [MicrochipTech/PIC32MZW1_Workshop#6]
I uploaded "PIC32MZW1_Curiosity_OOB code 1.2.6" to "the PIC32MZ W1 Curiosity Board".
the demo code has not been modified at all. 

According to the explanatory material, replace WIFI.CFG. 
then, when i connect the "https://pic-iot.com/pic32mzw1/aws/daba15b9482bab0a46696b77c497a915594da84c", the following error appears.
**"We couldn't retrieve recent data from your device. To connect to a network automatically, ensure the device is plugged in."**

The device seems to have acquired the IP normally.
But the web site doesn't find the device.
What steps should be taken to proceed?
Do I need to sign up and register with AWS?

Below is the uart debug message.
![image](https://user-images.githubusercontent.com/80269792/122544790-1dcbbe00-d068-11eb-8400-9945f1609bb3.png)

**Comment by gd91** [comment]
Please use the support system: https://microchipsupport.force.com/s/article/How-to-submit-a-case
