### ISSUE TITLE
SYS_WIFI_CTRLMSG enum member SYS_WIFI_GETCONFIG name changed

### ISSUE THREAD

**Issue by SamSiegelFutureElectronics** [MicrochipTech/PIC32MZW1_Workshop#7]
The example code and documentation for the "Build a platform from scratch" example refers to a member of the enum "SYS_WIFI_CTRLMSG" named "SYS_WIFI_GETCONFIG".
The name of this constant appears to have been redefined at some point, as the define for SYS_WIFI_CTRLMSG does not contain that name.  The closest I could find (and am assuming the member the code refers to) is "SYS_WIFI_GETWIFICONFIG".

**Comment by gd91** [comment]
fixed and updated.
